### PR TITLE
new update to the readme file

### PR DESCRIPTION
**Pull request by adityakalburgi**
done with the complete update of readme file

### CODE REVIEW

**Comment by KunjShah95** [comment]
is your requirement fulfilled?

**Review by KunjShah95 — APPROVED** [review]

**Comment by KunjShah95** [comment]
sir if u need any changes then comment it down so i will do it if not there any changes so will i get the hactoberfest rewards

**Comment by KunjShah95** [comment]
sir any update on it

**Comment by nikhilkalburgi** [comment]
Hi @KunjShah95 ,

You can make the following updates to the file:
1. Improve the table of contents. For example change numbers to bullet points.
2. Remove the License: repo not found.
3. Remove horizontal thick lines like shown below:
image

**Comment by KunjShah95** [comment]
ok sending u with all the changes done in few minutes

**Comment by KunjShah95** [comment]
[update_readme.md](https://github.com/user-attachments/files/17227558/update_readme.md)
here si the update done with all the changes u requored as the pull request is closed so i am attaching it here

**Comment by nikhilkalburgi** [comment]
Hi @KunjShah95 ,

Create a separate PR for your changes. The file you shared has some additional changes. Do not change anything else apart from what I have suggested (above 3 points).

**Comment by KunjShah95** [comment]
I HAVE CREATED A NEW PR KIDNLY CHECK IT

**Pull request merged**
